; Script generated by the HM NIS Edit Script Wizard.

; Trick for aborting if parameters are wrong
!ifndef TSNET4_VERSION
Abort
!endif

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "TressetteNetwork4"
!define PRODUCT_VERSION "${TSNET4_VERSION}"
!define PRODUCT_PUBLISHER "GtkDC Team"
!define PRODUCT_WEB_SITE "http://home.gna.org/tsnet4"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

!ifdef PYTHON
!define PYTHON_PATH_KEY "Software\Python\PythonCore\2.5\InstallPath"
!endif

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "..\COPYING"
; Components page
!ifdef PYTHON
!insertmacro MUI_PAGE_COMPONENTS
!endif
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "TressetteNetwork4"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
;!define MUI_FINISHPAGE_NOAUTOCLOSE
;!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Italian"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
!ifdef PYTHON
OutFile "tsnet4-${PRODUCT_VERSION}.exe"
!else
OutFile "tsnet4-${PRODUCT_VERSION}-no-python.exe"
!endif
InstallDir "$PROGRAMFILES\TressetteNetwork4"
ShowInstDetails show
ShowUnInstDetails show

Section "TressetteNetwork4" SEC01
  SectionIn RO
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "..\graphics.pyc"
  File "..\launcher.pyc"
  File "..\main.pyc"
  File "..\miscgui.pyc"
  File "..\objects.pyc"
  File "..\player.pyc"
  File "..\protocol.pyc"
  File "..\server.pyc"
  File "..\__init__.pyc"
  File "..\client.pyc"
  File "..\deck.pyc"
  SetOutPath "$INSTDIR\netframework"
  File "..\netframework\connection.pyc"
  File "..\netframework\interfaces.pyc"
  File "..\netframework\loop.pyc"
  File "..\netframework\miscnet.pyc"
  File "..\netframework\__init__.pyc"
  SetOutPath "$INSTDIR\cards"
  File "..\cards\piacentine1.jpg"
  File "..\cards\piacentine10.jpg"
  File "..\cards\piacentine11.jpg"
  File "..\cards\piacentine12.jpg"
  File "..\cards\piacentine13.jpg"
  File "..\cards\piacentine14.jpg"
  File "..\cards\piacentine15.jpg"
  File "..\cards\piacentine16.jpg"
  File "..\cards\piacentine17.jpg"
  File "..\cards\piacentine18.jpg"
  File "..\cards\piacentine19.jpg"
  File "..\cards\piacentine2.jpg"
  File "..\cards\piacentine20.jpg"
  File "..\cards\piacentine21.jpg"
  File "..\cards\piacentine22.jpg"
  File "..\cards\piacentine23.jpg"
  File "..\cards\piacentine24.jpg"
  File "..\cards\piacentine25.jpg"
  File "..\cards\piacentine26.jpg"
  File "..\cards\piacentine27.jpg"
  File "..\cards\piacentine28.jpg"
  File "..\cards\piacentine29.jpg"
  File "..\cards\piacentine3.jpg"
  File "..\cards\piacentine30.jpg"
  File "..\cards\piacentine31.jpg"
  File "..\cards\piacentine32.jpg"
  File "..\cards\piacentine33.jpg"
  File "..\cards\piacentine34.jpg"
  File "..\cards\piacentine35.jpg"
  File "..\cards\piacentine36.jpg"
  File "..\cards\piacentine37.jpg"
  File "..\cards\piacentine38.jpg"
  File "..\cards\piacentine39.jpg"
  File "..\cards\piacentine4.jpg"
  File "..\cards\piacentine40.jpg"
  File "..\cards\piacentine41.jpg"
  File "..\cards\piacentine5.jpg"
  File "..\cards\piacentine6.jpg"
  File "..\cards\piacentine7.jpg"
  File "..\cards\piacentine8.jpg"
  File "..\cards\piacentine9.jpg"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\TressetteNetwork4.lnk" "$INSTDIR\launcher.pyc"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Avvia server.lnk" "$INSTDIR\main.pyc" "standalone"

  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

!ifdef PYTHON
Section "Python 2.5" SEC02
  SetOutPath "$TEMP"
  SetOverwrite on
  File /oname=python.msi "python-2.5*.msi"

  ExecWait '"msiexec" /i "$TEMP\python.msi" /norestart /quiet'
  Delete "$TEMP\python.msi"
SectionEnd

Section "Pygame 1.8" SEC03
  SetOutPath "$TEMP"
  SetOverwrite on
  File /oname=pygame.msi "pygame-1.8*.msi"

  ExecWait '"msiexec" /i "$TEMP\pygame.msi" /norestart /quiet'
  Delete "$TEMP\pygame.msi"
SectionEnd

Section "wxPython 2.8" SEC04
  SetOutPath "$TEMP"
  SetOverwrite on
  File /oname=wxpython.exe "wxPython2.8*.exe"

  ExecWait '"$TEMP\wxpython.exe" /verysilent /norestart /suppressmsgboxes'
  Delete "$TEMP\wxpython.exe"
SectionEnd
!endif

Section -AdditionalIcons
  SetOutPath $INSTDIR
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Progetto TSNet4.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Disinstalla.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

!ifdef PYTHON
Function .onInit
  ReadRegStr $0 HKLM ${PYTHON_PATH_KEY} ""
  StrCmp $0 "" notPython contPy

  ReadRegStr $0 HKCU ${PYTHON_PATH_KEY} ""
  StrCmp $0 "" notPython

contPy:
  SectionGetFlags ${SEC02} $1
  IntOp $1 $1 - ${SF_SELECTED}
  SectionSetFlags ${SEC02} $1

notPython:
  IfFileExists "$0\Lib\site-packages\pygame*" 0 notPygame

  SectionGetFlags ${SEC03} $1
  IntOp $1 $1 - ${SF_SELECTED}
  SectionSetFlags ${SEC03} $1

notPygame:
  IfFileExists "$0\Lib\site-packages\wx.pth" 0 notWx

  SectionGetFlags ${SEC04} $1
  IntOp $1 $1 - ${SF_SELECTED}
  SectionSetFlags ${SEC04} $1

notWx:
FunctionEnd
!endif

; Section descriptions
!ifdef PYTHON
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} "Installa il gioco e tutti i relativi dati."
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} "Installa Python 2.5 per Windows."
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC03} "Installa la libreria Pygame - necessaria per il gioco."
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC04} "Installa la libreria wxPython - necessaria per l'interfaccia grafica."
!insertmacro MUI_FUNCTION_DESCRIPTION_END
!endif

;Function un.onUninstSuccess
;  HideWindow
;  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) � stato completamente rimosso dal tuo computer."
;FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Sei sicuro di voler completamente rimuovere $(^Name) e tutti i suoi componenti?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\deck.pyc"
  Delete "$INSTDIR\client.pyc"
  Delete "$INSTDIR\__init__.pyc"
  Delete "$INSTDIR\netframework\__init__.pyc"
  Delete "$INSTDIR\netframework\miscnet.pyc"
  Delete "$INSTDIR\netframework\loop.pyc"
  Delete "$INSTDIR\netframework\interfaces.pyc"
  Delete "$INSTDIR\netframework\connection.pyc"
  Delete "$INSTDIR\cards\piacentine9.jpg"
  Delete "$INSTDIR\cards\piacentine8.jpg"
  Delete "$INSTDIR\cards\piacentine7.jpg"
  Delete "$INSTDIR\cards\piacentine6.jpg"
  Delete "$INSTDIR\cards\piacentine5.jpg"
  Delete "$INSTDIR\cards\piacentine41.jpg"
  Delete "$INSTDIR\cards\piacentine40.jpg"
  Delete "$INSTDIR\cards\piacentine4.jpg"
  Delete "$INSTDIR\cards\piacentine39.jpg"
  Delete "$INSTDIR\cards\piacentine38.jpg"
  Delete "$INSTDIR\cards\piacentine37.jpg"
  Delete "$INSTDIR\cards\piacentine36.jpg"
  Delete "$INSTDIR\cards\piacentine35.jpg"
  Delete "$INSTDIR\cards\piacentine34.jpg"
  Delete "$INSTDIR\cards\piacentine33.jpg"
  Delete "$INSTDIR\cards\piacentine32.jpg"
  Delete "$INSTDIR\cards\piacentine31.jpg"
  Delete "$INSTDIR\cards\piacentine30.jpg"
  Delete "$INSTDIR\cards\piacentine3.jpg"
  Delete "$INSTDIR\cards\piacentine29.jpg"
  Delete "$INSTDIR\cards\piacentine28.jpg"
  Delete "$INSTDIR\cards\piacentine27.jpg"
  Delete "$INSTDIR\cards\piacentine26.jpg"
  Delete "$INSTDIR\cards\piacentine25.jpg"
  Delete "$INSTDIR\cards\piacentine24.jpg"
  Delete "$INSTDIR\cards\piacentine23.jpg"
  Delete "$INSTDIR\cards\piacentine22.jpg"
  Delete "$INSTDIR\cards\piacentine21.jpg"
  Delete "$INSTDIR\cards\piacentine20.jpg"
  Delete "$INSTDIR\cards\piacentine2.jpg"
  Delete "$INSTDIR\cards\piacentine19.jpg"
  Delete "$INSTDIR\cards\piacentine18.jpg"
  Delete "$INSTDIR\cards\piacentine17.jpg"
  Delete "$INSTDIR\cards\piacentine16.jpg"
  Delete "$INSTDIR\cards\piacentine15.jpg"
  Delete "$INSTDIR\cards\piacentine14.jpg"
  Delete "$INSTDIR\cards\piacentine13.jpg"
  Delete "$INSTDIR\cards\piacentine12.jpg"
  Delete "$INSTDIR\cards\piacentine11.jpg"
  Delete "$INSTDIR\cards\piacentine10.jpg"
  Delete "$INSTDIR\cards\piacentine1.jpg"
  Delete "$INSTDIR\server.pyc"
  Delete "$INSTDIR\protocol.pyc"
  Delete "$INSTDIR\player.pyc"
  Delete "$INSTDIR\objects.pyc"
  Delete "$INSTDIR\miscgui.pyc"
  Delete "$INSTDIR\main.pyc"
  Delete "$INSTDIR\launcher.pyc"
  Delete "$INSTDIR\graphics.pyc"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Disinstalla.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\Progetto TSNet4.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\TressetteNetwork4.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\Avvia server.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR\netframework"
  RMDir "$INSTDIR\cards"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
;  SetAutoClose true
SectionEnd
